[project]
name = "telegram-bot-sample"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "python-decouple>=3.8",
    "python-telegram-bot>=22.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
